"""Scheduler/storage protocols so pure nodes do not depend on local paths."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any, BinaryIO, Protocol

import polars as pl

from iter8ml.domain.manifests import ArtifactRef, ProductManifest, RunManifest


class ProductWriterProtocol(Protocol):
    def add_file(self, source: Path, *, relative_path: str, kind: str) -> ArtifactRef: ...
    def commit(self, manifest: ProductManifest) -> ProductManifest: ...
    def abort(self) -> None: ...


class ArtifactStore(Protocol):
    def exists(self, product_id: str) -> bool: ...
    def read_manifest(self, product_id: str) -> ProductManifest: ...
    def read_verified_manifest(self, product_id: str, *, deep: bool = True) -> ProductManifest: ...
    def begin(self, product_id: str, *, product_type: str, name: str) -> ProductWriterProtocol: ...
    def open_artifact(self, ref: ArtifactRef) -> BinaryIO: ...
    def verify(self, product_id: str, *, deep: bool = False) -> dict[str, object]: ...
    def list_products(self, product_type: str | None = None) -> Iterable[ProductManifest]: ...


class CatalogStore(Protocol):
    def register_product(self, manifest: ProductManifest) -> None: ...
    def register_run(self, manifest: RunManifest) -> None: ...
    def query(self, sql: str, parameters: Sequence[Any] = ()) -> pl.DataFrame: ...


class LockManager(Protocol):
    def acquire(self, key: str) -> Any: ...
