"""AbstractModel Protocol for structural subtyping."""

from typing import Protocol

import numpy as np


class AbstractModel(Protocol):
    def fit(self, X: np.ndarray, y: np.ndarray, **kwargs) -> None: ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, X: np.ndarray) -> np.ndarray | None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...

    @property
    def model_name(self) -> str: ...
